### ISSUE TITLE
Would like to know how to setup neovim as external editor in Unity 2022.1.0b7 and/or 2020.3.28f1.

### ISSUE THREAD

**Issue by nyngwang** [Iovesophy/dotfiles#22]
Hi, I'm a reader from your post: https://zenn.dev/_kazuya/articles/21474b28909327. As title. Are you still developing Unity via NeoVim?

**Comment by Iovesophy** [comment]
Hey @nyngwang  and thanks for raising up this issue.

>developing Unity via NeoVim?

btw , I forgot about this problem until a while ago, but now I have a good idea and implemented it.
It can be solved by using AppleScript.
I'll publish it to Github later.
